### ISSUE TITLE
dataset divide

### ISSUE THREAD

**Issue by guanjian729** [qqueing/DeepSpeaker-pytorch#3]
hello，i can download dataset from this URL:http://www.robots.ox.ac.uk/~vgg/data/voxceleb/download.sh  with this commond : ./download.sh list.txt         but all download audio is in a file.How can I separate them with  speakers？？？can you understand?  my English is awfu. very thanks.

**Comment by TTTJJJWWW** [comment]
你解决这个问题了吗？
