### ISSUE TITLE
How to prepare the dataset

### ISSUE THREAD

**Issue by xinli94** [qqueing/DeepSpeaker-pytorch#9]
Hi,

Thanks for the great implementation! I am wondering how should I download voxceleb dataset. What is the expected directory structure? And also could you give us an example of test_pairs file?

Best,
Xin

**Comment by xinli94** [comment]
Solved! Ended up generating testing pairs manually, since I did not find official test_pairs for voxceleb2

**Comment by TTTJJJWWW** [comment]
Hi! how do you fix this issue? @xinli94
